#############################################################################
## Services are now located in separate files, in the services directory.  ##
#############################################################################

# Common network used by all services
networks: 
  default:
    name: "traefik-network"
    external: true
  cloudflare-transport:
    name: "cloudflare-transport"
    
  
