services:
  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    restart: always
    volumes:
      - $HOST_MEDIA_PATH:/torrents
      - $HOST_CONFIG_PATH/bazarr:/config
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}