services:
  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    restart: always
    volumes:
      - bazarrmedia:/torrents
      - bazarrconfig:/config
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}

volumes:
  bazarrmedia:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_MEDIA_PATH
  bazarrconfig:
    driver: local-persist
    driver_opts:
      mountpoint: $CONFIG_PATH/bazarr