services:
  calibre:
    image: ghcr.io/linuxserver/calibre
    container_name: calibre
    restart: always
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - PASSWORD=${CALIBRE_PASSWORD}
      - CLI_ARGS=
    volumes:
      - calibreconfig:/config
      - calibremedia:/torrents

volumes:
  calibremedia:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_MEDIA_PATH
  calibreconfig:
    driver: local-persist
    driver_opts:
      mountpoint: $CONFIG_PATH/calibre