services:
  calibre:
    image: ghcr.io/linuxserver/calibre
    container_name: calibre
    restart: always
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - PASSWORD=${CALIBRE_PASSWORD}
      - CLI_ARGS=
    volumes:
      - $HOST_CONFIG_PATH/calibre:/config
      - $HOST_MEDIA_PATH:/torrents
