services:
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web:nightly
    container_name: calibre-web
    restart: always
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/mods:universal-calibre
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    volumes:
      - calibreconfig:/config
      - calibremedia:/torrents

volumes:
  calibremedia:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_MEDIA_PATH
  calibreconfig:
    driver: local-persist
    driver_opts:
      mountpoint: $CONFIG_PATH/calibre