services:
  deluge:
    image: ghcr.io/linuxserver/deluge
    container_name: deluge
    restart: always
    volumes:
      - $HOST_MEDIA_PATH:/torrents
      - $HOST_CONFIG_PATH/deluge:/config
      - $HOST_MEDIA_PATH/$DOWNLOAD_SUBFOLDER:/downloads
      - $HOST_MEDIA_PATH_2:/media
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}