services:
  flood:
    image: jesec/flood:master
    container_name: flood
    restart: always
    depends_on:
      - deluge
    user: ${PUID}:${PGID}
    command:
      - --auth=none
      - --dehost=${DELUGE_HOST}
      - --deport=58846
      - --deuser=flood
      - --depass=${FLOOD_PASSWORD}
      - --rundir=/config
    volumes:
      - $HOST_CONFIG_PATH/flood:/config
      - $HOST_MEDIA_PATH:/torrents
      - $HOST_MEDIA_PATH/$DOWNLOAD_SUBFOLDER:/downloads
      - /etc/localtime:/etc/localtime:ro
