services:
  gluetun:
    image: ghcr.io/qdm12/gluetun
    container_name: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VPN_TYPE=wireguard
      - VPN_SERVICE_PROVIDER=custom
      # For Wireguard
      - VPN_ENDPOINT_IP=${WIREGUARD_ENDPOINT}
      - VPN_ENDPOINT_PORT=${WIREGUARD_PORT}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESS=${WIREGUARD_ADDRESS}
    volumes:
      - $HOST_CONFIG_PATH/gluetun:/config
