services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VPN_TYPE=openvpn
      # For Wireguard
      #- VPN_ENDPOINT_IP=${WIREGUARD_ENDPOINT}
      #- VPN_ENDPOINT_PORT=${WIREGUARD_PORT}
      #- WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      #- WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      #- WIREGUARD_ADDRESS=${WIREGUARD_ADDRESS}
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER=fKLl0BbMtF5sdEue
      - OPENVPN_PASSWORD=EcSrJabWcKSMrguy0C2TmRz3IrdwtL42
      - SERVER_COUNTRIES=Switzerland
    volumes:
      - $HOST_CONFIG_PATH/gluetun:/config
