services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VPN_TYPE=openvpn
      # For Wireguard
      #- VPN_ENDPOINT_IP=${WIREGUARD_ENDPOINT}
      #- VPN_ENDPOINT_PORT=${WIREGUARD_PORT}
      #- WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      #- WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      #- WIREGUARD_ADDRESS=${WIREGUARD_ADDRESS}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
    volumes:
      - $HOST_CONFIG_PATH/gluetun:/config
