services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    restart: always
    volumes:
      - $HOST_CONFIG_PATH/heimdall:/config
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}