services:
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    restart: always
    volumes:
      - $HOST_CONFIG_PATH/jacket:/config
      - $HOST_MEDIA_PATH:/downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - RUN_OPTS='-FlareSolverrURL="http://flaresolverr:8191"'
