services:
  jdownloader:
    image: jlesage/jdownloader-2
    container_name: jdownloader
    restart: always
    volumes:
      - jdownloaderconfig:/config
      - jdownloadermedia:/output
    environment:
      - USER_ID=${PUID}
      - GROUP_ID=${PGID}
      - TZ=${TZ}

volumes:
  jdownloadermedia:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_MEDIA_PATH/$DOWNLOAD_SUBFOLDER
  jdownloaderconfig:
    driver: local-persist
    driver_opts:
      mountpoint: $CONFIG_PATH/jdownloader
