services:
  jdownloader:
    image: jlesage/jdownloader-2
    container_name: jdownloader
    restart: always
    volumes:
      - $HOST_CONFIG_PATH/jdownloader:/config
      - $HOST_MEDIA_PATH/$DOWNLOAD_SUBFOLDER:/output
    environment:
      - USER_ID=${PUID}
      - GROUP_ID=${PGID}
      - TZ=${TZ}
