services:
  kavita:
    image: kizaing/kavita:latest
    container_name: kavita
    restart: always
    volumes:
      - $HOST_CONFIG_PATH/kavita:/kavita/config
      - $HOST_MEDIA_PATH:/torrents
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
    # Wait for https://github.com/Kareadita/Kavita/issues/301 to be resolved
    #user: "${PUID}:${PGID}"