services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    restart: always
    volumes:
      - $HOST_CONFIG_PATH/kavita:/kavita/config
      - $HOST_MEDIA_PATH:/torrents
      - $HOST_MEDIA_PATH_2:/media
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
      - PGID=${PGID}
      - PUID=${PUID}
    # Wait for https://github.com/Kareadita/Kavita/issues/301 to be resolved
    #user: "${PUID}:${PGID}"
