services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    restart: always
    volumes:
      - kavitaconfig:/config
      - kavitamedia:/torrents
      - $HOST_MEDIA_PATH_2:/media
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
      - PGID=${PGID}
      - PUID=${PUID}
    # Wait for https://github.com/Kareadita/Kavita/issues/301 to be resolved
    #user: "${PUID}:${PGID}"

volumes:
  kavitamedia:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_MEDIA_PATH
  kavitaconfig:
    driver: local-persist
    driver_opts:
      mountpoint: $CONFIG_PATH/kavita