services:
  komga:
    image: gotson/komga
    container_name: komga
    restart: always
    volumes:
      - $HOST_CONFIG_PATH/komga:/config
      - $HOST_MEDIA_PATH:/torrents
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
    user: "${PUID}:${PGID}"