services:
  lidarr:
    image: ghcr.io/linuxserver/lidarr:develop
    container_name: lidarr
    restart: always
    volumes:
      - lidarrconfig:/config
      - lidarrmedia:/torrents
      - $HOST_MEDIA_PATH_2:/media
      - lidarrdownloads:/downloads
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}

volumes:
  lidarrmedia:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_MEDIA_PATH
  lidarrconfig:
    driver: local-persist
    driver_opts:
      mountpoint: $CONFIG_PATH/lidarr
  lidarrdownloads:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_MEDIA_PATH/$DOWNLOAD_SUBFOLDER