services:
  lidarr:
    image: ghcr.io/linuxserver/lidarr:develop
    container_name: lidarr
    restart: always
    volumes:
      - $HOST_CONFIG_PATH/lidarr:/config
      - $HOST_MEDIA_PATH:/torrents
      - $HOST_MEDIA_PATH_2:/media
      - $HOST_MEDIA_PATH/$DOWNLOAD_SUBFOLDER:/downloads
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
