services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    restart: always
    user: ${PUID}:${PGID}
    command:
      - serve
    environment:
      - TZ=${TZ}
      - NTFY_BASE_URL=https://ntfy.${TRAEFIK_DOMAIN}
      - NTFY_LISTEN_HTTP=:2586
      - NTFY_BEHIND_PROXY=true
      - NTFY_CACHE_FILE=/var/cache/ntfy/cache.db
      - NTFY_ATTACHMENT_CACHE_DIR=/var/cache/ntfy/attachments
      - NTFY_AUTH_FILE=/conf/user.db
      - NTFY_AUTH_DEFAULT_ACCESS=deny-all
    volumes:
      - ntfycache:/var/cache/ntfy
      - ntfyconf:/conf
    
volumes:
  ntfycache:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/ntfy/cache
  ntfyconf:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/ntfy/conf
