services:
  ombi:
    image: ghcr.io/linuxserver/ombi
    container_name: ombi
    restart: always
    volumes:
      - $HOST_CONFIG_PATH/ombi:/config
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - BASE_URL=/