services:
  overseerr:
    image: ghcr.io/linuxserver/overseerr
    container_name: overseerr
    restart: always
    volumes:
      - $HOST_CONFIG_PATH/overseerr:/config
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
