services:
  overseerr:
    image: ghcr.io/linuxserver/overseerr
    container_name: overseerr
    restart: always
    volumes:
      - overseerrconfig:/config
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}

volumes:
  overseerrconfig:
    driver: local-persist
    driver_opts:
      mountpoint: $CONFIG_PATH/overseerr