services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    restart: always
    network_mode: host
    devices:
      - /dev/dri:/dev/dri # for hardware transcoding
    volumes:
      - $HOST_CONFIG_PATH/Plex:/config
      - $HOST_MEDIA_PATH:/torrents
      - /dev/shm:/transcode
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - VERSION=latest