services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    restart: always
    network_mode: host
    volumes:
      - $HOST_CONFIG_PATH/plex:/config
      - $HOST_MEDIA_PATH:/torrents
      - $HOST_MEDIA_PATH_2:/media
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - VERSION=latest
