services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    restart: always
    network_mode: host
    ports:
      - "32400:32400"
      - "32400:32400/udp"
      - "32469:32469"
      - "32469:32469/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    volumes:
      - $HOST_CONFIG_PATH/Plex:/config
      - $HOST_MEDIA_PATH:/torrents
      - $HOST_MEDIA_PATH_2:/media
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - VERSION=latest