services:
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: always
    volumes:
      - $HOST_CONFIG_PATH/prowlarr:/config
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}