services:
  qbittorrent:
    image: ghcr.io/hotio/qbittorrent
    container_name: qbittorrent
    restart: always
    volumes:
      - qbittorrentmedia:/torrents
      - qbittorrentmedia2:/media
      - qbittorrentconfig:/config
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}

volumes:
  qbittorrentmedia:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_MEDIA_PATH
  qbittorrentmedia2:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_MEDIA_PATH_2
  qbittorrentconfig:
    driver: local-persist
    driver_opts:
      mountpoint: $CONFIG_PATH/qbittorrent
