services:
  radarr:
    image: ghcr.io/linuxserver/radarr:develop
    container_name: radarr
    restart: always
    volumes:
      - radarrconfig:/config
      - radarrmedia:/torrents
      - radarrmovies:/movies
      - radarrdownloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}

volumes:
  radarrmedia:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_MEDIA_PATH
  radarrconfig:
    driver: local-persist
    driver_opts:
      mountpoint: $CONFIG_PATH/radarr
  radarrmovies:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_MEDIA_PATH/movies
  radarrdownloads:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_MEDIA_PATH/$DOWNLOAD_SUBFOLDER