services:
  readarr:
    image: lscr.io/linuxserver/readarr:nightly
    container_name: readarr
    restart: always
    volumes:
      - readarrconfig:/config
      - readarrmedia:/torrents
      - readarrdownloads:/downloads
      - $HOST_MEDIA_PATH_2:/media
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}

volumes:
  readarrmedia:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_MEDIA_PATH
  readarrconfig:
    driver: local-persist
    driver_opts:
      mountpoint: $CONFIG_PATH/readarr
  readarrdownloads:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_MEDIA_PATH/$DOWNLOAD_SUBFOLDER