services:
  readarr:
    image: lscr.io/linuxserver/readarr:nightly
    container_name: readarr
    restart: always
    volumes:
      - $HOST_CONFIG_PATH/readarr:/config
      - $HOST_MEDIA_PATH:/torrents
      - $HOST_MEDIA_PATH/$DOWNLOAD_SUBFOLDER:/downloads
      - $HOST_MEDIA_PATH_2:/media
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
