services:
  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: seerr
    restart: always
    init: true
    user: "1001:1001"
    volumes:
      - seerrconfig:/app/config
    environment:
      - TZ=${TZ}

volumes:
  seerrconfig:
    driver: local-persist
    driver_opts:
      mountpoint: $CONFIG_PATH/overseerr