services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr:develop
    container_name: sonarr
    restart: always
    volumes:
      - sonarrconfig:/config
      - sonarrmedia:/torrents
      - sonarrdownloads:/downloads
      - sonarrmedia2:/media
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}

volumes:
  sonarrmedia:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_MEDIA_PATH
  sonarrmedia2:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_MEDIA_PATH_2
  sonarrconfig:
    driver: local-persist
    driver_opts:
      mountpoint: $CONFIG_PATH/sonarr
  sonarrdownloads:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_MEDIA_PATH/$DOWNLOAD_SUBFOLDER
