services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr:develop
    container_name: sonarr
    restart: always
    volumes:
      - $HOST_CONFIG_PATH/sonarr:/config
      - $HOST_MEDIA_PATH:/torrents
      - $HOST_MEDIA_PATH/$DOWNLOAD_SUBFOLDER:/downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
