services:
  tautulli:
    image: ghcr.io/linuxserver/tautulli
    container_name: tautulli
    restart: always
    volumes:
      - $HOST_CONFIG_PATH/tautulli:/config
      - $HOST_CONFIG_PATH:/logs:ro # Inside of tautulli, bind to logs via "/logs/Plex Media Server/Logs"
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}