services:
  traefik:
    image: traefik
    container_name: traefik
    restart: always
    command:
      - --certificatesresolvers.le.acme.email=${ACME_MAIL}
      - "--accesslog=true"
      - "--accesslog.filePath=/config/access.log"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik:ro
      - $HOST_CONFIG_PATH/traefik:/config
    environment:
      - TRAEFIK_DOMAIN=${TRAEFIK_DOMAIN}
      - TZ=${TZ}

