services:
  traefik:
    image: traefik
    container_name: traefik
    restart: always
    command:
      - --certificatesresolvers.le.acme.email=${ACME_MAIL}
      - "--accesslog=true"
      - "--accesslog.filePath=/config/access.log"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefiketc:/etc/traefik:ro
      - traefikconfig:/config
    environment:
      - TRAEFIK_DOMAIN=${TRAEFIK_DOMAIN}
      - TZ=${TZ}
    networks:
      - default
      - cloudflare-transport

volumes:
  traefikconfig:
    driver: local-persist
    driver_opts:
      mountpoint: $CONFIG_PATH/traefik
  traefiketc:
    driver: local-persist
    driver_opts:
      mountpoint: $CONFIG_PATH/traefik-etc

