services:
  uptime-kula:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - uptimekuma:/app/data
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    healthcheck:
      test: wget --spider http://localhost:2375/version || exit 1
      interval: "29s"
      timeout: "5s"
      retries: 3
      start_period: "21s"
    environment:
      - CONTAINERS=1
      - POST=0

volumes:
  uptimekuma:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/uptime-kuma
